apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-demo
  labels:
    app: flask-docker-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-docker-demo
  template:
    metadata:
      labels:
        app: flask-docker-demo
    spec:
      containers:
      - name: flask-docker-demo
        image: arechberger/flask-docker-demo:0.0.1
        ports:
        - containerPort: 8000